### ISSUE TITLE
Dead link on Lecture 1

### ISSUE THREAD

**Issue by ryanyord** [pachterlab/BI-BE-CS-183-2023#2]
On the last slide of lecture 1:

● Videos of Gilbert Strang’s course on linear algebra, 1999.
Hyperlink (at least for me) is dead.

I think [this](https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/download/) would be a suitable replacement.

**Comment by lakigigar** [comment]
Thanks for noting that. Excellent suggestion- I've replaced the link.
