### ISSUE TITLE
Solutions to homework exercises?

### ISSUE THREAD

**Issue by sebgoti** [pachterlab/BI-BE-CS-183-2023#4]
First of all I would like to thank you for all the amazing teaching material. As a self-learner, it can be difficult to follow the notes and exercises on my own and was wondering if the solutions could be available as well. This can help to see if the concepts from the homework were well understood.

**Comment by tarachari3** [comment]
Unfortunately, since we still actively use parts of these problems in class, we can't release solutions publicly. But happy to hear you've found these materials to be helpful!
